//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amazonMechanicalTurk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobData
    {
        public int JobID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> AdditionalID { get; set; }
    
        public virtual JobAdditional JobAdditional { get; set; }
    }
}
