//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amazonMechanicalTurk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInfo
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string JobExplanation { get; set; }
        public bool JobActive { get; set; }
        public int JobCountRequired { get; set; }
        public Nullable<int> JobCountDone { get; set; }
        public byte[] TimeSt { get; set; }
    }
}
