//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amazonMechanicalTurk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int SolutionsID { get; set; }
        public int JobID { get; set; }
        public int SolutionByUserID { get; set; }
        public string Solution1 { get; set; }
        public byte[] TimeSt { get; set; }
    }
}
