//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amazonMechanicalTurk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBmechanicalTurkEntities : DbContext
    {
        public DBmechanicalTurkEntities()
            : base("name=DBmechanicalTurkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobAdditional> JobAdditionals { get; set; }
        public virtual DbSet<JobData> JobDatas { get; set; }
        public virtual DbSet<JobInfo> JobInfoes { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
